name: GenerateSeeds

on:
  push:
    branches:
      - master
      - develop
      - 'dev/**'
      - 'version/**'
jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
    - name: login github docker repo
      run: docker login docker.pkg.github.com -u $GITHUB_ACTOR -p ${{ secrets.GITHUB_TOKEN }}
    - uses: actions/checkout@v1
    - name: setup dir
      run: |
        mkdir -p 'dist/zip'
        touch MASTER_VERSION
        echo HEAD > REF_NAME
    - name: set version
      if: contains(github.ref, 'refs/heads/version/')
      run: |
        echo $GITHUB_REF |awk -F '/' '{print $NF}' > MASTER_VERSION
        cp MASTER_VERSION REF_NAME
    - name: generate_yml
      run: |
        export VERSION=`cat MASTER_VERSION`
        docker-compose run server_seed
    - name: generate_zip
      run: |
        REF_NAME=`cat REF_NAME`
        zip -j ./dist/zip/${{github['sha']}}@${REF_NAME}.zip ./dist/*.yml
    - name: PublishToAWSS3
      uses: opspresso/action-s3-sync@master
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: "ap-northeast-1"
        FROM_PATH: "./dist/zip/"
        DEST_PATH: "s3://leaptrigger-admin/staging/"
        OPTIONS: '--metadata github_ref=${{ github.ref }},github_actor=${{ github.actor }}'
    - name: Slack Notification
      uses: tokorom/action-slack-incoming-webhook@master
      env:
        INCOMING_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      with:
        text: マスターデータのS3アップロードだよ！
        attachments: |
          [
            {
              "color": "good",
              "author_name": "${{ github.actor }}",
              "author_icon": "${{ github.event.sender.avatar_url }}",
              "fields": [
                {
                  "title": "Commit Message",
                  "value": "${{ env.COMMIT_MESSAGE }}"
                },
                {
                  "title": "GitHub Actions URL",
                  "value": "${{ github.event.repository.url }}/actions/runs/${{ github.run_id }}"
                },
                {
                  "title": "Compare URL",
                  "value": "${{ github.event.compare }}"
                }
              ]
            }
          ]: 
  slack:
    name: Slack
    needs: PublishToAWSS3 # 最後のJOBを指定
    runs-on: ubuntu-latest
    if: always() # alwaysを指定
    steps:
      - uses: technote-space/workflow-conclusion-action@v1 # Workflow の結果を取得するアクション
      - uses: 8398a7/action-slack@v2
        with:
          status: ${{ env.WORKFLOW_CONCLUSION }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} 

