name: GenerateSeeds

on:
  push:
    branches:
      - master
      - develop
      - 'dev/**'
      - 'version/**'

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
    - name: login github docker repo
    - uses: actions/checkout@v1
      run: docker login docker.pkg.github.com -u $GITHUB_ACTOR -p ${{ secrets.GITHUB_TOKEN }}
    - name: setup dir
      run: |
        mkdir -p 'dist/zip'
        touch MASTER_VERSION
        echo HEAD > REF_NAME
    - name: set version
      if: contains(github.ref, 'refs/heads/version/')
      run: |
        echo $GITHUB_REF |awk -F '/' '{print $NF}' > MASTER_VERSION
        cp MASTER_VERSION REF_NAME
    - name: generate_yml
      run: |
        export VERSION=`cat MASTER_VERSION`
        docker-compose run server_seed
    - name: generate_zip
      run: |
        REF_NAME=`cat REF_NAME`
        zip -j ./dist/zip/${{github['sha']}}@${REF_NAME}.zip ./dist/*.yml
    - name: Publish to AWS S3
      uses: opspresso/action-s3-sync@master
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: "ap-northeast-1"
        FROM_PATH: "./dist/zip/"
        DEST_PATH: "s3://hogehoge-level-design/"
        OPTIONS: '--metadata github_ref=${{ github.ref }},github_actor=${{ github.actor }}'
